name: CI (main)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-fe:
    name: Build Vue Frontend (main)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myHDFW-frontend-vite
    strategy:
      matrix:
        node-version: [ 18.19.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        name: Install dependencies
      - run: npm run build --if-present
        name: Build
  unittest-fe:
    name: Run Vue Unit-Tests (main)
    runs-on: ubuntu-latest
    needs: build-dev
    defaults:
      run:
        working-directory: myHDFW-frontend-vite
    strategy:
      matrix:
        node-version: [ 18.19.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        name: Install dependencies
      - run: npm run test:unit
        name: Run Unit-Tests
  e2eTest-fe:
    name: Run e2e tests (main)
    runs-on: ubuntu-latest
    needs: build-main
    defaults:
      run:
        working-directory: myHDFW-frontend-vite
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run e2e-tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome ./myHDFW-frontend-vite/src/systemtest/"
  build-be:
    name: Build Java Backend (main)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myhdfw-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  test-be:
    name: Run Java Tests (main)
    runs-on: ubuntu-latest
    needs: build-be
    defaults:
      run:
        working-directory: myhdfw-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Java Unit-Tests
        run: mvn test