name: Node.js CI

on:
  push:
    paths:
      - ./myHDFW-frontend-vite/**
    branches:
      - main
      - dev
  pull_request:
    paths:
      - ./myHDFW-frontend-vite/**
    branches:
      - main
      - dev

jobs:
  build-vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./myHDFW-frontend-vite
    strategy:
      matrix:
        node-version: [18.19.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
