name: CI (Pull Request to dev)

on:
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build-fe:
    name: Build Vue Frontend (dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myHDFW-frontend-vite
    strategy:
      matrix:
        node-version: [ 18.19.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        name: Install dependencies
      - run: npm run build --if-present
        name: Build
  unittest-fe:
    name: Run Vue Unit-Tests (dev)
    runs-on: ubuntu-latest
    needs: build-fe
    defaults:
      run:
        working-directory: myHDFW-frontend-vite
    strategy:
      matrix:
        node-version: [ 18.19.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        name: Install dependencies
      - run: npm run test:unit
        name: Run Unit-Tests
  integrationtest-fe:
    name: Run Vue Integration tests (dev)
    runs-on: ubuntu-latest
    needs: build-fe
    defaults:
      run:
        working-directory: myHDFW-frontend-vite
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        name: Install dependencies
      - name: Run dev server
        run: npm run dev &
      - name: Run e2e-tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome:headless ./myHDFW-frontend-vite/src/integrationtest/"
      - name: Stop dev server
        run: kill $(lsof -t -i:5173)
        if: always()
  build-be:
    name: Build Java Backend (dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myhdfw-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -P skip-test
  test-be:
    name: Run Spring Tests (dev)
    runs-on: ubuntu-latest
    needs: build-be
    defaults:
      run:
        working-directory: myhdfw-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven Tests
        run: mvn test -Dspring.profiles.active=test
