name: CI (Push to Dev)

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build-fe:
    name: Build Vue Frontend (dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myHDFW-frontend-vite
    strategy:
      matrix:
        node-version: [18.19.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        name: Install dependencies
      - run: npm run build --if-present
        name: Build
  build-be:
    name: Build Java Backend (dev)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myhdfw-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml